-- ==========================================
-- 1. TABEL UTAMA (Induk)
-- ==========================================

-- Tabel Sekolah
CREATE TABLE IF NOT EXISTS sekolah (
  npsn TEXT PRIMARY KEY,
  nama_sekolah TEXT NOT NULL
);

-- Tabel Akun Superadmin
CREATE TABLE IF NOT EXISTS akun_superadmin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

-- Tabel Akun Guru
CREATE TABLE IF NOT EXISTS akun_guru (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  nama_guru TEXT
);

-- ==========================================
-- 2. TABEL PENGGUNA TERKAIT (Anak)
-- ==========================================

-- Tabel Akun Admin Sekolah
CREATE TABLE IF NOT EXISTS akun_admin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  npsn TEXT REFERENCES sekolah(npsn) ON DELETE CASCADE
);

-- Tabel Akun Siswa
CREATE TABLE IF NOT EXISTS akun_siswa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  
  npsn TEXT REFERENCES sekolah(npsn) ON DELETE CASCADE,
  
  nik TEXT,
  nama_lengkap TEXT,
  jenis_kelamin TEXT CHECK (jenis_kelamin IN ('L', 'P')),
  tanggal_lahir DATE
);

-- ==========================================
-- 3. TABEL KEGIATAN & KONTEN
-- ==========================================

-- Tabel Soal
-- Catatan: Kolom is_active dan durasi_menit sudah digabungkan di sini
CREATE TABLE IF NOT EXISTS soal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Relasi ke Guru Pembuat
  guru_id BIGINT REFERENCES akun_guru(id),
  
  -- Atribut Soal
  tipe_soal TEXT DEFAULT 'pilihan_ganda' CHECK (tipe_soal IN ('pilihan_ganda', 'pilihan_ganda_kompleks', 'benar_salah', 'menjodohkan')),
  konten_pertanyaan TEXT NOT NULL, 
  
  -- Struktur JSON untuk Opsi Jawaban
  opsi_jawaban JSONB NOT NULL, 
  
  -- Kunci Jawaban
  kunci_jawaban TEXT NOT NULL,

  -- Pengaturan Ujian/Akses
  is_active BOOLEAN DEFAULT TRUE, -- Default TRUE agar soal langsung muncul
  durasi_menit INTEGER DEFAULT 60 -- Default 1 jam
);

-- Tabel Jawaban Siswa
CREATE TABLE IF NOT EXISTS jawaban_siswa (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  siswa_id BIGINT REFERENCES akun_siswa(id),
  soal_id BIGINT REFERENCES soal(id),
  jawaban_dipilih TEXT,
  ragu_ragu BOOLEAN DEFAULT FALSE,
  tanggal_submit TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ==========================================
-- 4. ROW LEVEL SECURITY (RLS)
-- ==========================================

ALTER TABLE sekolah ENABLE ROW LEVEL SECURITY;
ALTER TABLE akun_superadmin ENABLE ROW LEVEL SECURITY;
ALTER TABLE akun_admin ENABLE ROW LEVEL SECURITY;
ALTER TABLE akun_guru ENABLE ROW LEVEL SECURITY;
ALTER TABLE akun_siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE soal ENABLE ROW LEVEL SECURITY;
ALTER TABLE jawaban_siswa ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5. POLICIES (Akses Publik/Development)
-- ==========================================

-- Policy Sekolah
DROP POLICY IF EXISTS "Public Access Sekolah" ON sekolah;
CREATE POLICY "Public Access Sekolah" ON sekolah FOR ALL USING (true);

-- Policy Superadmin
DROP POLICY IF EXISTS "Public Access Superadmin" ON akun_superadmin;
CREATE POLICY "Public Access Superadmin" ON akun_superadmin FOR ALL USING (true);

-- Policy Admin
DROP POLICY IF EXISTS "Public Access Admin" ON akun_admin;
CREATE POLICY "Public Access Admin" ON akun_admin FOR ALL USING (true);

-- Policy Guru
DROP POLICY IF EXISTS "Public Access Guru" ON akun_guru;
CREATE POLICY "Public Access Guru" ON akun_guru FOR ALL USING (true);

-- Policy Siswa
DROP POLICY IF EXISTS "Public Access Siswa" ON akun_siswa;
CREATE POLICY "Public Access Siswa" ON akun_siswa FOR ALL USING (true);

-- Policy Soal
DROP POLICY IF EXISTS "Public Access Soal" ON soal;
CREATE POLICY "Public Access Soal" ON soal FOR ALL USING (true);

-- Policy Jawaban
DROP POLICY IF EXISTS "Public Access Jawaban" ON jawaban_siswa;
CREATE POLICY "Public Access Jawaban" ON jawaban_siswa FOR ALL USING (true);

-- ==========================================
-- 6. SEED DATA (Data Awal)
-- ==========================================

-- Seed Superadmin
INSERT INTO akun_superadmin (username, password)
VALUES ('bangbin', 'bangbin123')
ON CONFLICT (username) DO NOTHING;

-- Seed Sekolah
INSERT INTO sekolah (npsn, nama_sekolah)
VALUES ('1234', 'SDN 1234')
ON CONFLICT (npsn) DO NOTHING;

-- Seed Admin Sekolah
INSERT INTO akun_admin (username, password, npsn)
VALUES ('Admin1234', 'Admin1234', '1234')
ON CONFLICT (username) DO NOTHING;

-- Seed Guru
INSERT INTO akun_guru (nama_guru, username, password)
VALUES ('BangbinGuru', 'BangbinGuru', 'Guru1234')
ON CONFLICT (username) DO NOTHING;

-- Seed Siswa
INSERT INTO akun_siswa (username, password, npsn, nik, nama_lengkap, jenis_kelamin)
VALUES ('123456789', '123456789', '1234', '12345678', 'Siswa 1 SDN 1234', 'L')
ON CONFLICT (username) DO NOTHING;
