
create table if not exists sekolah (
  npsn text primary key,
  nama_sekolah text not null
);


create table if not exists akun_superadmin (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null
);

create table if not exists akun_admin (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  npsn text references sekolah(npsn) on delete cascade
);


create table if not exists akun_guru (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  nama_guru text
);


create table if not exists akun_siswa (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  
  npsn text references sekolah(npsn) on delete cascade,
  
  nik text,
  nama_lengkap text,
  jenis_kelamin text check (jenis_kelamin in ('L', 'P')),
  tanggal_lahir date
);

create table if not exists soal (
  id bigint generated by default as identity primary key,
  
  -- ID Guru Pembuat
  guru_id bigint references akun_guru(id),
  

  tipe_soal text default 'pilihan_ganda' check (tipe_soal in ('pilihan_ganda', 'pilihan_ganda_kompleks', 'benar_salah', 'menjodohkan')),
  
  konten_pertanyaan text not null, -- Support HTML/Gambar
  
  -- Struktur JSON untuk Opsi Jawaban (A, B, C, D)
  opsi_jawaban jsonb not null, 
  
  -- Kunci Jawaban
  kunci_jawaban text not null
);

-- 7. Tabel Hasil Jawaban Siswa
create table if not exists jawaban_siswa (
  id bigint generated by default as identity primary key,
  siswa_id bigint references akun_siswa(id),
  soal_id bigint references soal(id),
  jawaban_dipilih text,
  ragu_ragu boolean default false,
  tanggal_submit timestamp with time zone default now()
);

-- Konfigurasi Row Level Security (RLS)
alter table sekolah enable row level security;
alter table akun_superadmin enable row level security;
alter table akun_admin enable row level security;
alter table akun_guru enable row level security;
alter table akun_siswa enable row level security;
alter table soal enable row level security;
alter table jawaban_siswa enable row level security;



drop policy if exists "Public Access Sekolah" on sekolah;
create policy "Public Access Sekolah" on sekolah for all using (true);

drop policy if exists "Public Access Superadmin" on akun_superadmin;
create policy "Public Access Superadmin" on akun_superadmin for all using (true);

drop policy if exists "Public Access Admin" on akun_admin;
create policy "Public Access Admin" on akun_admin for all using (true);

drop policy if exists "Public Access Guru" on akun_guru;
create policy "Public Access Guru" on akun_guru for all using (true);

drop policy if exists "Public Access Siswa" on akun_siswa;
create policy "Public Access Siswa" on akun_siswa for all using (true);

drop policy if exists "Public Access Soal" on soal;
create policy "Public Access Soal" on soal for all using (true);

drop policy if exists "Public Access Jawaban" on jawaban_siswa;
create policy "Public Access Jawaban" on jawaban_siswa for all using (true);


INSERT INTO akun_superadmin (username, password)
VALUES ('bangbin', 'bangbin123')
ON CONFLICT (username) DO NOTHING;


INSERT INTO sekolah (npsn, nama_sekolah)
VALUES ('1234', 'SDN 1234')
ON CONFLICT (npsn) DO NOTHING;


INSERT INTO akun_admin (username, password, npsn)
VALUES ('Admin1234', 'Admin1234', '1234')
ON CONFLICT (username) DO NOTHING;


INSERT INTO akun_guru (nama_guru, username, password)
VALUES ('BangbinGuru', 'BangbinGuru', 'Guru1234')
ON CONFLICT (username) DO NOTHING;


INSERT INTO akun_siswa (username, password, npsn, nik, nama_lengkap, jenis_kelamin)
VALUES ('123456789', '123456789', '1234', '12345678', 'Siswa 1 SDN 1234', 'L')
ON CONFLICT (username) DO NOTHING;